name: zouz_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.1
  easy_localization: ^3.0.8
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.3
  go_router: ^17.1.0
  go_sell_sdk_flutter: ^2.4.29
  intl: ^0.20.2
  mobile_scanner: ^7.2.0
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  riverpod_annotation: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/

  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFUIDisplay-Regular.otf
        - asset: assets/fonts/SFUIDisplay-Light.ttf
          weight: 300
    - family: Noor
      fonts:
        - asset: assets/fonts/NoorRegular.ttf


